In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("movies.csv")

In [3]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [4]:
df.info

<bound method DataFrame.info of       index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction
1         1  300000000                  Adventure Fantasy Action
2         2  245000000                    Action Adventure Crime
3         3  250000000               Action Crime Drama Thriller
4         4  260000000          Action Adventure Science Fiction
...     ...        ...                                       ...
4798   4798     220000                     Action Crime Thriller
4799   4799       9000                            Comedy Romance
4800   4800          0             Comedy Drama Romance TV Movie
4801   4801          0                                       NaN
4802   4802          0                               Documentary

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995
1          http://disney.go.com/disneypictures/pirates/     285
2           http://www.sonypictures.com/movies/spectre/  206647
3                    http://www.thedarkknightrises.com/   49026
4                  http://movies.disney.com/john-carter   49529
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
0     culture clash future space war space colony so...                en
1     ocean drug abuse exotic island east india trad...                en
2            spy based on novel secret agent sequel mi6                en
3     dc comics crime fighter terrorist secret ident...                en
4     based on novel mars medallion space travel pri...                en
...                                                 ...               ...
4798  united states\u2013mexico barrier legs arms pa...                es
4799                                                NaN                en
4800  date love at first sight narration investigati...                en
4801                                                NaN                en
4802               obsession camcorder crush dream girl                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...
2     A cryptic message from Bond’s past sends him o...  107.376788  ...
3     Following the death of District Attorney Harve...  112.312950  ...
4     John Carter is a war-weary, former military ca...   43.926995  ...
...                                                 ...         ...  ...
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...
4802  Ever since the second grade when he first saw ...    1.929883  ...

     runtime                                   spoken_languages    status  \
0      162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1      169.0           [{"iso_639_1": "en", "name": "English"}]  Released
2      148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3      165.0           [{"iso_639_1": "en", "name": "English"}]  Released
4      132.0           [{"iso_639_1": "en", "name": "English"}]  Released
...      ...                                                ...       ...
4798    81.0      [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released
4799    85.0                                                 []  Released
4800   120.0           [{"iso_639_1": "en", "name": "English"}]  Released
4801    98.0           [{"iso_639_1": "en", "name": "English"}]  Released
4802    90.0           [{"iso_639_1": "en", "name": "English"}]  Released

                                                tagline  \
0                           Enter the World of Pandora.
1        At the end of the world, the adventure begins.
2                                 A Plan No One Escapes
3                                       The Legend Ends
4                  Lost in our world, found in another.
...                                                 ...
4798  He didn't come looking for trouble, but troubl...
4799  A newlywed couple's honeymoon is upended by th...
4800                                                NaN
4801                           A New Yorker in Shanghai
4802                                                NaN

                                         title vote_average vote_count  \
0                                       Avatar          7.2      11800
1     Pirates of the Caribbean: At World's End          6.9       4500
2                                      Spectre          6.3       4466
3                        The Dark Knight Rises          7.6       9106
4                                  John Carter          6.1       2124
...                                        ...          ...        ...
4798                               El Mariachi          6.6        238
4799                                 Newlyweds          5.9          5
4800                 Signed, Sealed, Delivered          7.0          6
4801                          Shanghai Calling          5.7          7
4802                         My Date with Drew          6.3         16

                                                   cast  \
0     Sam Worthington Zoe Saldana Sigourney Weaver S...
1     Johnny Depp Orlando Bloom Keira Knightley Stel...
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
3     Christian Bale Michael Caine Gary Oldman Anne ...
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...
...                                                 ...
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...

                                                   crew           director
0     [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1     [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2     [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3     [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4     [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton
...                                                 ...                ...
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...   Robert Rodriguez
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...       Edward Burns
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...        Scott Smith
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...        Daniel Hsia
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...   Brian Herzlinger

[4803 rows x 24 columns]>

In [5]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='str')

In [6]:
df.shape

(4803, 24)

In [7]:
df.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [8]:
df=df.drop_duplicates().reset_index(drop=True)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df=df[['title','overview','genres','tagline','vote_average','popularity']]

In [11]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Enter the World of Pandora.,7.2,150.437577
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,"At the end of the world, the adventure begins.",6.9,139.082615
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,A Plan No One Escapes,6.3,107.376788
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,The Legend Ends,7.6,112.312950
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,"Lost in our world, found in another.",6.1,43.926995
...,...,...,...,...,...,...
4798,El Mariachi,El Mariachi just wants to play his guitar and ...,Action Crime Thriller,"He didn't come looking for trouble, but troubl...",6.6,14.269792
4799,Newlyweds,A newlywed couple's honeymoon is upended by th...,Comedy Romance,A newlywed couple's honeymoon is upended by th...,5.9,0.642552
4800,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",Comedy Drama Romance TV Movie,NaN,7.0,1.444476
4801,Shanghai Calling,When ambitious New York attorney Sam is sent t...,NaN,A New Yorker in Shanghai,5.7,0.857008
4802,My Date with Drew,Ever since the second grade when he first saw ...,Documentary,NaN,6.3,1.929883

In [12]:
df.isnull().sum()

title             0
overview          3
genres           28
tagline         844
vote_average      0
popularity        0
dtype: int64

In [13]:
df=df.dropna(subset=['title'])

In [14]:
df['overview']=df['overview'].fillna('')

In [15]:
df.iloc[0]['genres']

'Action Adventure Fantasy Science Fiction'

In [16]:
import ast

In [17]:
def format_genres(value):
    if pd.isna(value):
        return ''

    if isinstance(value, str):
        try:
            value = ast.literal_eval(value)
        except (ValueError, SyntaxError):
            return value  # Already a plain genre string

    return " ".join(
        genre['name']
        for genre in value
        if isinstance(genre, dict) and 'name' in genre
    )

df['genres'] = df['genres'].apply(format_genres)

In [18]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Enter the World of Pandora.,7.2,150.437577
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,"At the end of the world, the adventure begins.",6.9,139.082615
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,A Plan No One Escapes,6.3,107.376788
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,The Legend Ends,7.6,112.312950
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,"Lost in our world, found in another.",6.1,43.926995

In [19]:
df['tagline']=df['tagline'].fillna(' ')

In [20]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [21]:
df['tags']=df['overview']+" "+df['genres']+" "+df['tagline']

In [22]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Enter the World of Pandora.,7.2,150.437577,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,"At the end of the world, the adventure begins.",6.9,139.082615,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,A Plan No One Escapes,6.3,107.376788,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,The Legend Ends,7.6,112.312950,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,"Lost in our world, found in another.",6.1,43.926995,"John Carter is a war-weary, former military ca..."

In [23]:
pip install nltk

Requirement already satisfied: nltk in c:\users\asus\appdata\local\python\pythoncore-3.12-64\lib\site-packages (3.10.4)
Requirement already satisfied: defusedxml in c:\users\asus\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\asus\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in c:\users\asus\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\asus\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from nltk) (2026.9.29)
Requirement already satisfied: tqdm in c:\users\asus\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from nltk) (4.70.1)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\asus\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python312\site-packages (from tqdm->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [25]:
nltk.download('stopwords')
nltk.download('WordNet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading WordNet: Package 'WordNet' not found in
[nltk_data]     index

False

In [26]:
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [27]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [31]:
def preprocess_text(text):
    text=str(text).lower()
    text=re.sub(r'[^a-zA-Z\s]','',text)

    words=text.split()
    words=[word for word in words if word not in stop_words]

    words=[lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [32]:
df['tags']=df['tags'].apply(preprocess_text)

In [33]:
df=df.reset_index(drop=True)

In [34]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()
indices

title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    stop_words='english'
)

In [40]:
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [41]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 132035 stored elements and shape (4803, 5000)>

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
def recommend(title, n=10):
    if title not in indices:
        return('Movie not found')

    idx= indices[title]
    sim_score=cosine_similarity(tfidf_matrix(idx)).flatten()
    similar_idx=sim_score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [ ]:
def recommend(title, n=10):
    if title not in indices:
        return "Movie not found"

    idx = indices[title]
    sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    sim_score[idx] = -1  # Exclude the movie itself
    similar_idx = sim_score.argsort()[::-1][:n]

    return df["title"].iloc[similar_idx]

TypeError: 'csr_matrix' object is not callable